/* =========================================================
 * スペイン語 単語デッキ（西検 5級 → 4級）
 *
 *  1語の書き方：
 *    id    保存用の名前（変えない）
 *    s     区間（sections の id）
 *    w     単語（つづり）
 *    pos   品詞 n＝名詞 v＝動詞 adj＝形容詞 adv＝副詞
 *    g     名詞の性 m＝男性 f＝女性（冠詞 el / la を自動でつける）
 *    art   冠詞を上書きするとき（el agua など）
 *    ja    意味
 *    ex    例文 [スペイン語, 日本語]。{ } で囲んだ所がこの単語（活用した形でもよい）
 *    clue  予想の手がかり
 *            cog   英語と似ている（同じ祖先）
 *            trap  英語と似ているのに意味がちがう（lure＝思わず選ぶ意味）
 *            parts 語の部品
 *            ctx   場面（例文を見せて意味を予想）
 *    memo  覚え方・使い方のヒント（任意）
 *
 *  例文と手がかりは、このアプリのためのオリジナル。
 *  区間の級は目安（西検は公式の単語リストを公開していない）。
 * ========================================================= */
window.VOCAB_DECK = {
  id: 'spanish',
  title: 'スペイン語 単語',
  brand: '¡VAMOS!',
  sub: '西検 5級 → 4級',
  skin: 'espana',
  sound: 'es',
  lang: 'es',
  sections: [
    { id: 'k5', name: '5級（顔見知り）', known: true },
    { id: 'k4', name: '4級' }
  ],
  words: [
    /* ---------------- 5級：顔見知り ---------------- */
    { id: 'casa', s: 'k5', w: 'casa', pos: 'n', g: 'f', ja: '家', ex: ['Mi {casa} es pequeña.', '私の家は小さい。'],
      clue: { t: 'ctx', text: '🏠 Mi casa es tu casa. は「ようこそ」の決まり文句。直訳すると「私の◯◯はあなたの◯◯」' } },
    { id: 'agua', s: 'k5', w: 'agua', pos: 'n', g: 'f', art: 'el', ja: '水', ex: ['El {agua} está fría.', '水が冷たい。'],
      clue: { t: 'cog', text: '英語の aquarium（水族館）・aqua と同じ祖先' },
      memo: '女性名詞なのに el agua。強く読む a で始まる女性名詞は、言いにくいので el にする（fría は女性形のまま）' },
    { id: 'libro', s: 'k5', w: 'libro', pos: 'n', g: 'm', ja: '本', ex: ['Este {libro} es muy interesante.', 'この本はとてもおもしろい。'],
      clue: { t: 'cog', text: '英語の library（図書館）の lib- と同じ祖先' } },
    { id: 'mesa', s: 'k5', w: 'mesa', pos: 'n', g: 'f', ja: 'テーブル・机', ex: ['El gato está debajo de la {mesa}.', '猫がテーブルの下にいる。'],
      clue: { t: 'cog', text: '英語の mesa は「上が平らな台地」。その形から…' } },
    { id: 'perro', s: 'k5', w: 'perro', pos: 'n', g: 'm', ja: '犬', ex: ['Mi {perro} se llama Coco.', '私の犬はココという名前です。'],
      clue: { t: 'ctx', text: '🦴 「ワンワン（guau, guau）」と鳴く動物' } },
    { id: 'gato', s: 'k5', w: 'gato', pos: 'n', g: 'm', ja: '猫', ex: ['Tengo un {gato} negro.', '黒い猫を飼っている。'],
      clue: { t: 'cog', text: '英語の cat と同じ祖先（g と c は入れかわりやすい）' } },
    { id: 'hombre', s: 'k5', w: 'hombre', pos: 'n', g: 'm', ja: '男の人', ex: ['Ese {hombre} es mi profesor.', 'あの男の人は私の先生です。'],
      clue: { t: 'cog', text: 'ラテン語の homo（人）から。英語の human と親戚' } },
    { id: 'mujer', s: 'k5', w: 'mujer', pos: 'n', g: 'f', ja: '女の人', ex: ['La {mujer} de la foto es mi tía.', '写真の女の人は私のおばです。'],
      clue: { t: 'ctx', text: '👫 hombre（男の人）と対になる語。la がつくので女性名詞' } },
    { id: 'nino', s: 'k5', w: 'niño', pos: 'n', g: 'm', ja: '男の子・子ども', ex: ['El {niño} juega en el parque.', '男の子が公園で遊んでいる。'],
      clue: { t: 'ctx', text: '🌊 エルニーニョ現象（El Niño）は、クリスマスのころに起きるので「神の◯◯」と呼ばれた' },
      memo: '女の子は niña。-o が男性、-a が女性' },
    { id: 'dia', s: 'k5', w: 'día', pos: 'n', g: 'm', ja: '日', ex: ['Hoy es un buen {día}.', '今日はいい日だ。'],
      clue: { t: 'cog', text: 'Buenos días（おはよう）の días。英語の diary（日記）と同じ祖先' },
      memo: '-a で終わるのに男性名詞（el día）。例外として覚える' },
    { id: 'noche', s: 'k5', w: 'noche', pos: 'n', g: 'f', ja: '夜', ex: ['Buenas {noches}, hasta mañana.', 'おやすみ、また明日。'],
      clue: { t: 'cog', text: '英語の night と同じ祖先（n…ch ／ n…ght）' } },
    { id: 'hoy', s: 'k5', w: 'hoy', pos: 'adv', ja: '今日', ex: ['¿Qué día es {hoy}?', '今日は何曜日？'],
      clue: { t: 'ctx', text: '📅 カレンダーを見ながら聞く質問' } },
    { id: 'manana', s: 'k5', w: 'mañana', pos: 'adv', ja: '明日', ex: ['Hasta {mañana}.', 'また明日。'],
      clue: { t: 'ctx', text: '👋 夕方、友だちと別れるときのあいさつ' },
      memo: 'la mañana と名詞で使うと「朝」。明日の朝＝mañana por la mañana' },
    { id: 'comer', s: 'k5', w: 'comer', pos: 'v', ja: '食べる', ex: ['¿{Comemos} juntos?', 'いっしょに食べようか？'],
      clue: { t: 'ctx', text: '🍽️ 昼の12時、同僚に声をかける' }, memo: 'comida（食べ物・食事）も同じ仲間' },
    { id: 'beber', s: 'k5', w: 'beber', pos: 'v', ja: '飲む', ex: ['¿Qué quieres {beber}?', '何を飲みたい？'],
      clue: { t: 'cog', text: '英語の beverage（飲み物）と同じ祖先' } },
    { id: 'hablar', s: 'k5', w: 'hablar', pos: 'v', ja: '話す', ex: ['¿{Hablas} español?', 'スペイン語を話せる？'],
      clue: { t: 'ctx', text: '🗣️ 旅行先で、言葉が通じるか確かめる' } },
    { id: 'vivir', s: 'k5', w: 'vivir', pos: 'v', ja: '住む・生きる', ex: ['{Vivo} en Tokio.', '東京に住んでいる。'],
      clue: { t: 'cog', text: '英語の vivid（生き生きした）、survive（生きのびる）と同じ祖先' } },
    { id: 'tener', s: 'k5', w: 'tener', pos: 'v', ja: '持っている', ex: ['{Tengo} dos hermanos.', '兄弟が2人いる。'],
      clue: { t: 'cog', text: '英語の contain・maintain の -tain（保つ）と同じ祖先' },
      memo: '私は＝tengo（不規則）。「兄弟がいる」「おなかがすいている」も tener で言う' },
    { id: 'ir', s: 'k5', w: 'ir', pos: 'v', ja: '行く', ex: ['{Voy} a la escuela en tren.', '電車で学校に行く。'],
      clue: { t: 'ctx', text: '🚃 ¡Vamos!（さあ、◯◯う！）も、この動詞の仲間' },
      memo: '形が大きく変わる：voy, vas, va, vamos, vais, van' },
    { id: 'grande', s: 'k5', w: 'grande', pos: 'adj', ja: '大きい', ex: ['Madrid es una ciudad {grande}.', 'マドリードは大きな都市だ。'],
      clue: { t: 'cog', text: '英語の grand（壮大な）と同じ祖先' } },
    { id: 'pequeno', s: 'k5', w: 'pequeño', pos: 'adj', ja: '小さい', ex: ['Tengo un perro {pequeño}.', '小さい犬を飼っている。'],
      clue: { t: 'ctx', text: '🐕 チワワを見て。grande の反対' } },
    { id: 'bueno', s: 'k5', w: 'bueno', pos: 'adj', ja: '良い・おいしい', ex: ['Este café es muy {bueno}.', 'このコーヒーはとてもおいしい。'],
      clue: { t: 'ctx', text: '☀️ Buenos días（おはよう）の buenos' } },
    { id: 'nuevo', s: 'k5', w: 'nuevo', pos: 'adj', ja: '新しい', ex: ['Tengo un móvil {nuevo}.', '新しいスマホを持っている。'],
      clue: { t: 'cog', text: '英語の new・novel（新しい）と同じ祖先' } },
    { id: 'rojo', s: 'k5', w: 'rojo', pos: 'adj', ja: '赤い', ex: ['Me gusta el coche {rojo}.', 'その赤い車が好きだ。'],
      clue: { t: 'ctx', text: '🍅🚒 トマトや消防車の色' } },
    { id: 'padre', s: 'k5', w: 'padre', pos: 'n', g: 'm', ja: '父', ex: ['Mi {padre} es médico.', '父は医者です。'],
      clue: { t: 'cog', text: '英語の paternal（父の）、father と同じ祖先' } },
    { id: 'madre', s: 'k5', w: 'madre', pos: 'n', g: 'f', ja: '母', ex: ['Mi {madre} cocina muy bien.', '母は料理がとても上手だ。'],
      clue: { t: 'cog', text: '英語の maternal（母の）、mother と同じ祖先' } },
    { id: 'ciudad', s: 'k5', w: 'ciudad', pos: 'n', g: 'f', ja: '都市・町', ex: ['Barcelona es una {ciudad} bonita.', 'バルセロナはきれいな町だ。'],
      clue: { t: 'cog', text: '英語の city と同じ祖先' }, memo: '-dad で終わる名詞は女性名詞（la ciudad, la universidad）' },
    { id: 'tren', s: 'k5', w: 'tren', pos: 'n', g: 'm', ja: '電車・列車', ex: ['El {tren} sale a las ocho.', '電車は8時に出る。'],
      clue: { t: 'cog', text: '英語の train と同じ祖先' } },
    { id: 'escuela', s: 'k5', w: 'escuela', pos: 'n', g: 'f', ja: '学校', ex: ['Mi hermana va a la {escuela} a pie.', '妹は歩いて学校に行く。'],
      clue: { t: 'cog', text: '英語の school と同じ祖先（語頭の s- に e がつく）' },
      memo: 'スペイン語は s＋子音 で始められないので e をつける：escuela, estudiar, España' },
    { id: 'estudiar', s: 'k5', w: 'estudiar', pos: 'v', ja: '勉強する', ex: ['{Estudio} español todos los días.', '毎日スペイン語を勉強している。'],
      clue: { t: 'cog', text: '英語の study と同じ祖先（ここでも語頭に e）' } },
    { id: 'amigo', s: 'k5', w: 'amigo', pos: 'n', g: 'm', ja: '友だち', ex: ['Pedro es mi mejor {amigo}.', 'ペドロは私のいちばんの友だちだ。'],
      clue: { t: 'cog', text: '英語の amicable（友好的な）と同じ祖先' }, memo: '女性の友だちは amiga' },

    /* ---------------- 4級 ---------------- */
    { id: 'biblioteca', s: 'k4', w: 'biblioteca', pos: 'n', g: 'f', ja: '図書館', ex: ['Estudio en la {biblioteca}.', '図書館で勉強する。'],
      clue: { t: 'parts', text: 'biblio（本：英語の Bible と同じ）＋ teca（しまっておく所）' },
      memo: 'library に似た librería は「本屋」。ひっかけに注意' },
    { id: 'libreria', s: 'k4', w: 'librería', pos: 'n', g: 'f', ja: '本屋', ex: ['Compro libros en la {librería}.', '本屋で本を買う。'],
      clue: { t: 'trap', text: '英語の library に似ているけど…？ libro（本）＋ -ería（〜の店）', lure: '図書館' },
      memo: '-ería は「〜の店」：panadería（パン屋）、cafetería。図書館は biblioteca' },
    { id: 'exito', s: 'k4', w: 'éxito', pos: 'n', g: 'm', ja: '成功', ex: ['La fiesta fue un {éxito}.', 'パーティーは大成功だった。'],
      clue: { t: 'trap', text: '英語の exit に似ているけど…？ ヒット曲のことも「◯◯」と言う', lure: '出口' },
      memo: '出口は salida。éxito はヒット曲・成功' },
    { id: 'salida', s: 'k4', w: 'salida', pos: 'n', g: 'f', ja: '出口', ex: ['¿Dónde está la {salida}?', '出口はどこですか？'],
      clue: { t: 'ctx', text: '🚪 駅や空港の案内板に SALIDA と ENTRADA（入口）が並んでいる' }, memo: 'salir（出る）の名詞' },
    { id: 'estacion', s: 'k4', w: 'estación', pos: 'n', g: 'f', ja: '駅・季節', ex: ['La {estación} está cerca de mi casa.', '駅は家の近くにある。'],
      clue: { t: 'cog', text: '英語の station（駅）と同じ祖先。season（季節）とも似ている' },
      memo: '-ción で終わる名詞は女性名詞。「季節」の意味もある（las cuatro estaciones＝四季）' },
    { id: 'aeropuerto', s: 'k4', w: 'aeropuerto', pos: 'n', g: 'm', ja: '空港', ex: ['Vamos al {aeropuerto} en taxi.', 'タクシーで空港に行こう。'],
      clue: { t: 'parts', text: 'aero（空：英語の aero-plane）＋ puerto（港：英語の port）' } },
    { id: 'hambre', s: 'k4', w: 'hambre', pos: 'n', g: 'f', art: 'el', ja: '空腹', ex: ['Tengo mucha {hambre}.', 'とてもおなかがすいた。'],
      clue: { t: 'ctx', text: '🍽️ 午後2時。朝から何も食べていない…' },
      memo: 'tener hambre＝おなかがすいている。el hambre だけど女性名詞なので mucha' },
    { id: 'sed', s: 'k4', w: 'sed', pos: 'n', g: 'f', ja: 'のどの渇き', ex: ['Tengo {sed}. ¿Hay agua?', 'のどが渇いた。水ある？'],
      clue: { t: 'ctx', text: '🏜️ 真夏の砂漠を1時間歩いた…' }, memo: 'tener sed＝のどが渇いている（hambre と同じ形）' },
    { id: 'cumpleanos', s: 'k4', w: 'cumpleaños', pos: 'n', g: 'm', ja: '誕生日', ex: ['¡Feliz {cumpleaños}!', '誕生日おめでとう！'],
      clue: { t: 'parts', text: 'cumple（満たす）＋ años（年）。年をひとつ満たす日' }, memo: '単数も複数も同じ形（el cumpleaños）' },
    { id: 'invierno', s: 'k4', w: 'invierno', pos: 'n', g: 'm', ja: '冬', ex: ['En {invierno} hace mucho frío.', '冬はとても寒い。'],
      clue: { t: 'ctx', text: '❄️ 雪がふって、こたつが恋しい季節' }, memo: '英語の hibernate（冬眠する）と同じ祖先' },
    { id: 'verano', s: 'k4', w: 'verano', pos: 'n', g: 'm', ja: '夏', ex: ['En {verano} vamos a la playa.', '夏は海に行く。'],
      clue: { t: 'ctx', text: '🏖️ 海、かき氷、セミの声' } },
    { id: 'levantarse', s: 'k4', w: 'levantarse', pos: 'v', ja: '起きる・立ち上がる', ex: ['Me {levanto} a las siete.', '7時に起きる。'],
      clue: { t: 'cog', text: '英語の elevator・lever（持ち上げる）と同じ祖先。自分を持ち上げる…' },
      memo: '-se がつくと「自分を〜する」。me levanto＝私は（自分を）起こす' },
    { id: 'acostarse', s: 'k4', w: 'acostarse', pos: 'v', ja: '寝る（床につく）', ex: ['Me {acuesto} a las once.', '11時に寝る。'],
      clue: { t: 'ctx', text: '🌙 夜11時、ベッドに入る' },
      memo: 'o→ue に変わる（me acuesto）。levantarse（起きる）の反対' },
    { id: 'despertarse', s: 'k4', w: 'despertarse', pos: 'v', ja: '目を覚ます', ex: ['Me {despierto} a las seis.', '6時に目が覚める。'],
      clue: { t: 'ctx', text: '⏰ 朝6時、目覚まし時計（despertador）が鳴った' },
      memo: 'e→ie に変わる（me despierto）。起きる（levantarse）の前に目を覚ます' },
    { id: 'conocer', s: 'k4', w: 'conocer', pos: 'v', ja: '知っている（人・場所）', ex: ['¿{Conoces} a María?', 'マリアを知ってる？'],
      clue: { t: 'cog', text: '英語の recognize・cognition（認識）と同じ祖先' },
      memo: '会ったことがある・行ったことがある、の「知っている」。人には a をつける。私は＝conozco' },
    { id: 'saber', s: 'k4', w: 'saber', pos: 'v', ja: '知っている（情報）', ex: ['No {sé} su número de teléfono.', '彼の電話番号は知らない。'],
      clue: { t: 'cog', text: 'ホモ・サピエンス（賢い人）の sapiens と同じ祖先' },
      memo: '情報・やり方の「知っている」。私は＝sé。No sé.（わからない）はよく使う' },
    { id: 'empezar', s: 'k4', w: 'empezar', pos: 'v', ja: '始まる・始める', ex: ['La clase {empieza} a las nueve.', '授業は9時に始まる。'],
      clue: { t: 'ctx', text: '🔔 チャイムが鳴って、授業が…' }, memo: 'e→ie に変わる（empiezo）' },
    { id: 'volver', s: 'k4', w: 'volver', pos: 'v', ja: '戻る・帰る', ex: ['{Vuelvo} a casa a las seis.', '6時に家に帰る。'],
      clue: { t: 'cog', text: '英語の revolve（回転する）と同じ祖先。ぐるっと回って元の所へ' }, memo: 'o→ue に変わる（vuelvo）' },
    { id: 'llegar', s: 'k4', w: 'llegar', pos: 'v', ja: '着く', ex: ['El tren {llega} a las diez.', '電車は10時に着く。'],
      clue: { t: 'ctx', text: '🚉 電光掲示板の「到着」の欄（LLEGADAS）' } },
    { id: 'salir', s: 'k4', w: 'salir', pos: 'v', ja: '出る・出かける', ex: ['{Salgo} de casa a las ocho.', '8時に家を出る。'],
      clue: { t: 'ctx', text: '🚪 SALIDA（出口）と同じ仲間の動詞' }, memo: '私は＝salgo（不規則）' },
    { id: 'recordar', s: 'k4', w: 'recordar', pos: 'v', ja: '覚えている・思い出す', ex: ['No {recuerdo} su nombre.', '彼の名前を思い出せない。'],
      clue: { t: 'cog', text: '英語の record（記録する）と同じ祖先' }, memo: 'o→ue に変わる（recuerdo）。recuerdo は名詞で「思い出・おみやげ」' },
    { id: 'olvidar', s: 'k4', w: 'olvidar', pos: 'v', ja: '忘れる', ex: ['Siempre {olvido} mi paraguas.', 'いつも傘を忘れる。'],
      clue: { t: 'cog', text: '英語の oblivion（忘却）と同じ祖先' } },
    { id: 'ayudar', s: 'k4', w: 'ayudar', pos: 'v', ja: '手伝う・助ける', ex: ['¿Me {ayudas}?', '手伝ってくれる？'],
      clue: { t: 'ctx', text: '🆘 おぼれそうな人が叫ぶ「¡Ayuda!」' } },
    { id: 'pagar', s: 'k4', w: 'pagar', pos: 'v', ja: '払う', ex: ['¿Puedo {pagar} con tarjeta?', 'カードで払えますか？'],
      clue: { t: 'cog', text: '英語の pay と同じ祖先' } },
    { id: 'caro', s: 'k4', w: 'caro', pos: 'adj', ja: '（値段が）高い', ex: ['Este reloj es muy {caro}.', 'この時計はとても高い。'],
      clue: { t: 'ctx', text: '💸 値札を見て思わず「¡Qué caro!」' }, memo: '背が高いは alto。値段だけ caro' },
    { id: 'barato', s: 'k4', w: 'barato', pos: 'adj', ja: '安い', ex: ['La fruta es {barata} aquí.', 'ここは果物が安い。'],
      clue: { t: 'ctx', text: '🛍️ 1ユーロショップで「¡Qué barato!」' } },
    { id: 'cansado', s: 'k4', w: 'cansado', pos: 'adj', ja: '疲れた', ex: ['Estoy muy {cansado}.', 'とても疲れた。'],
      clue: { t: 'ctx', text: '😮‍💨 10時間働いて、家に帰ってソファに倒れこむ' }, memo: 'いまの状態なので ser ではなく estar を使う' },
    { id: 'cerca', s: 'k4', w: 'cerca', pos: 'adv', ja: '近くに', ex: ['El hotel está {cerca} del mar.', 'ホテルは海の近くにある。'],
      clue: { t: 'ctx', text: '🚶 歩いて5分で着く' }, memo: '〜の近くに＝cerca de（de＋el → del）' },
    { id: 'lejos', s: 'k4', w: 'lejos', pos: 'adv', ja: '遠くに', ex: ['Mi casa está {lejos} de la escuela.', '家は学校から遠い。'],
      clue: { t: 'ctx', text: '✈️ 東京からマドリードまで、飛行機で14時間' }, memo: 'cerca（近くに）の反対' },
    { id: 'siempre', s: 'k4', w: 'siempre', pos: 'adv', ja: 'いつも', ex: ['{Siempre} desayuno en casa.', 'いつも家で朝ごはんを食べる。'],
      clue: { t: 'ctx', text: '☕ 毎朝かならず、一日も欠かさず' } },
    { id: 'temprano', s: 'k4', w: 'temprano', pos: 'adv', ja: '（時間が）早く', ex: ['Mañana me levanto {temprano}.', '明日は早く起きる。'],
      clue: { t: 'cog', text: '英語の temporary・tempo（時間）と同じ祖先' }, memo: '速さの「速く」は rápido。時間の「早く」が temprano' },
    { id: 'todavia', s: 'k4', w: 'todavía', pos: 'adv', ja: 'まだ', ex: ['{Todavía} estoy en casa.', 'まだ家にいる。'],
      clue: { t: 'ctx', text: '⏳ 「もう出た？」と聞かれて「いや、◯◯家にいる」' } }
  ]
};
