/* =========================================================
 * WORD AVENUE（英単語）デッキ「塾プリント10月9日」— Lesson 7
 *
 *  単語・品詞・意味・英英定義（def）は塾で配布されたプリントから（利用者の確認のうえで内蔵）。
 *  プリントの誤植は直した（oversesas → overseas、abel → able）。
 *  例文・予想の手がかり・覚え方は、このアプリのためのオリジナル。
 *  ref はプリントの番号。網かけの語（Part 1 の 6・9・14、Part 2 の 14・15 など）もそのまま入れた。
 *  形式は docs/単語データの作り方.md。英語のデッキは名詞の性（g）がいらない。
 *  clue.t = 'def' は、英英定義（def）を手がかりにして意味を予想する。defJa は英英定義の日本語訳（答えたあと・説明欄で見せる）。
 * ========================================================= */
window.VOCAB_DECK = {
  id: 'juku-1009',
  app: 'en',
  title: '塾プリント10月9日',
  brand: 'WORD AVENUE',
  sub: '英単語・Lesson 7',
  book: '塾プリント',
  lang: 'en',
  skin: 'avenue',
  sound: 'us',
  /* 難しめの語（見出し語ではない）：英英定義・例文の中で点線 → タップで意味のバルーン */
  gloss: {
    'label': 'ラベル・札',
    'cloth': '布',
    'particular': '特定の',
    'sleeves': '袖（sleeve の複数形）',
    'collar': 'えり',
    'clothing': '衣類',
    'goods': '品物・商品',
    'quantities': '量（quantity の複数形）',
    'process': '過程・手順',
    'produce': '生産する',
    'produces': '生産する（produce）',
    'likely': '〜しそうな・ありそうな',
    'paid': '支払われる（pay の過去分詞）',
    'based': 'based on 〜＝〜にもとづいて',
    'receives': '受け取る（receive）',
    'severe': '厳しい',
    'unpleasant': '不快な・いやな',
    'activity': '活動・作業',
    'needle': '針',
    'thread': '糸',
    'causing': '引き起こす（cause）',
    'damage': '損害・害',
    'especially': 'とくに',
    'environment': '環境',
    'apart': 'ばらばらに',
    'suddenly': '突然・急に',
    'fail': 'fail to do＝〜しない・〜しそこなう',
    'spending': '（お金を）使うこと（spend）',
    'costing': '費用がかかること（cost）',
    'completely': '完全に',
    'purpose': '目的',
    'treat': '扱う',
    'unfairly': '不公平に・不当に',
    'continuing': '続いている（continue）',
    'wider': 'より広い（wide の比較級）',
    'rise': '上がる',
    'accident': '事故',
    'desert': '砂漠',
    'smoking': '喫煙',
    'storm': '嵐',
    'hidden': '隠れた・見えない',
    'costs': '費用・コスト（cost の複数形）',
    'introduce': '紹介する',
    'earthquake': '地震',
    'terrible': 'ひどい・恐ろしい',
    'battery': '電池',
    'brands': 'ブランド（brand の複数形）',
    'factory': '工場',
    'cancel': '中止する・取り消す',
    'sweater': 'セーター',
    'missed': '乗り遅れた（miss の過去形）',
    'spent': '使った（spend の過去分詞）',
    'stay': 'stay up late＝夜ふかしする',
    'police': '警察',
    'wore': '着ていた（wear の過去形）',
    'taught': '教えた（teach の過去形）',
    'weather': '天気'
  },
  sections: [
    { id: 'P1', name: 'Lesson 7 Part 1', ref: 'No.1〜15' },
    { id: 'P2', name: 'Lesson 7 Part 2', ref: 'No.1〜15' },
    { id: 'P3', name: 'Lesson 7 Part 3', ref: 'No.1〜9' },
    { id: 'P4', name: 'Lesson 7 Part 4', ref: 'No.1〜9' }
  ],
  words: [
    /* ---------------- Part 1 ---------------- */
    { id: 'tag', s: 'P1', ref: 'No.1', w: 'tag', pos: 'n', ja: '札', def: 'a small label made of cloth or paper', defJa: '布や紙でできた小さなラベル',
      ex: ['Check the {tag} on your shirt to see where it was made.', 'シャツの札を見て、どこで作られたか確かめて。'],
      clue: { t: 'def' }, memo: 'price tag＝値札。服の内側についている「タグ」' },
    { id: 'industry', s: 'P1', ref: 'No.2', w: 'industry', pos: 'n', ja: '産業', def: 'businesses that produce a particular type of thing', defJa: '特定の種類のものを生産する事業（の全体）',
      ex: ['The car {industry} is very important in Japan.', '日本では自動車産業がとても重要だ。'],
      clue: { t: 'def' }, memo: '形容詞は industrial（産業の）。industrious（勤勉な）と区別' },
    { id: 'polo', s: 'P1', ref: 'No.3', w: 'polo', pos: 'n', ja: 'ポロ（ポロシャツ）', def: '[polo shirt] a shirt with short sleeves, a collar, and a few buttons', defJa: '［polo shirt］半袖で、えりと少しのボタンがついたシャツ',
      ex: ['He wore a white {polo} shirt.', '彼は白いポロシャツを着ていた。'],
      clue: { t: 'def' }, memo: 'もとは、馬に乗って行う球技「ポロ」の選手が着たシャツ' },
    { id: 'canadian', s: 'P1', ref: 'No.4', w: 'Canadian', pos: 'adj', ja: 'カナダの',
      ex: ['She is {Canadian}, but she lives in Tokyo.', '彼女はカナダ人だが、東京に住んでいる。'],
      clue: { t: 'ctx', text: '🍁 国旗にメープルの葉がある国' }, memo: 'Canada の形容詞。国名と同じく大文字で始める。「カナダ人」の意味にもなる' },
    { id: 'garment', s: 'P1', ref: 'No.5', w: 'garment', pos: 'n', ja: '衣服', def: 'a piece of clothing', defJa: '衣服の1点（服1枚）',
      ex: ['This factory makes {garments} for many brands.', 'この工場は多くのブランドの衣服を作っている。'],
      clue: { t: 'def' }, memo: 'clothes より改まった語。garment factory＝縫製工場' },
    { id: 'manufacture', s: 'P1', ref: 'No.6', w: 'manufacture', pos: 'v', ja: 'を製造する', def: 'to make goods in large quantities by using machines', defJa: '機械を使って、品物を大量に作ること',
      ex: ['The company {manufactures} shoes in Vietnam.', 'その会社はベトナムで靴を製造している。'],
      clue: { t: 'def' }, memo: 'manu（手）＋ fact（作る）。もとは「手で作る」。名詞も同じ形（製造）' },
    { id: 'bangladesh', s: 'P1', ref: 'No.7', w: 'Bangladesh', pos: 'n', ja: 'バングラデシュ',
      ex: ['Many of our clothes are made in {Bangladesh}.', '私たちの服の多くはバングラデシュで作られている。'],
      clue: { t: 'ctx', text: '🗺️ インドの東どなりにある、南アジアの国。衣料品の生産で有名' }, memo: '首都はダッカ。形容詞は Bangladeshi' },
    { id: 'production', s: 'P1', ref: 'No.8', w: 'production', pos: 'n', ja: '生産・製造', def: 'the process of making things', defJa: 'ものを作る過程',
      ex: ['{Production} of the new phone will start next month.', '新しい電話の生産は来月始まる。'],
      clue: { t: 'def' }, memo: '動詞は produce、作られた物は product（製品）' },
    { id: 'maker', s: 'P1', ref: 'No.9', w: 'maker', pos: 'n', ja: '製造業者', def: 'a company that makes or produces something', defJa: '何かを作ったり生産したりする会社',
      ex: ['This company is a famous toy {maker}.', 'この会社は有名なおもちゃメーカーだ。'],
      clue: { t: 'def' }, memo: 'make ＋ -er（〜するもの）。カタカナの「メーカー」' },
    { id: 'tend', s: 'P1', ref: 'No.10', w: 'tend', pos: 'v', ja: '（〜する）傾向がある', def: '[tend to do] to be likely; usually do', defJa: '［tend to do］〜しそうである。たいてい〜する',
      ex: ['Prices {tend} to rise in winter.', '冬は値段が上がる傾向がある。'],
      clue: { t: 'def' }, memo: '名詞は tendency（傾向）。後ろは to ＋ 動詞の原形' },
    { id: 'wage', s: 'P1', ref: 'No.11', w: 'wage', pos: 'n', ja: '賃金', def: 'money that a worker is paid based on the number of hours, days, etc., that he or she works', defJa: '働いた時間や日数などに応じて、働く人に支払われるお金',
      ex: ['The workers asked for higher {wages}.', '労働者たちは、もっと高い賃金を求めた。'],
      clue: { t: 'def' }, memo: '時給・日給のように、働いた時間で払われるお金。salary（給料）との違いに注意' },
    { id: 'salary', s: 'P1', ref: 'No.12', w: 'salary', pos: 'n', ja: '給料', def: 'the money a person receives for his or her work', defJa: '人が自分の仕事に対して受け取るお金',
      ex: ["My sister's {salary} went up this year.", '姉の給料は今年上がった。'],
      clue: { t: 'def' }, memo: 'ふつうは月給・年俸。wage（時間で払う賃金）と区別' },
    { id: 'lets_say', s: 'P1', ref: 'No.13', w: "let's say", use: "let's say ＋ 文", pos: 'phr', ja: '仮に…としよう',
      ex: ["{Let's say} you have 1,000 yen. What would you buy?", '仮に1000円持っているとしよう。何を買う？'],
      clue: { t: 'ctx', text: '💭 たとえ話を始めるときの決まり文句' }, memo: 'say は「言う」ではなく「たとえば」の意味で使われている' },
    { id: 'look_into', s: 'P1', ref: 'No.14', w: 'look into', use: 'look into A', pos: 'phr', ja: 'Aについて調査する',
      ex: ['The police are {looking into} the accident.', '警察はその事故を調査している。'],
      clue: { t: 'parts', text: 'look（見る）＋ into（〜の中へ）' }, memo: '= investigate。look at（〜を見る）、look for（〜を探す）と区別' },
    { id: 'tend_to', s: 'P1', ref: 'No.15', w: 'tend to', use: 'tend to ＋ 動詞の原形', pos: 'phr', ja: 'doする傾向がある',
      ex: ['Young people {tend to} stay up late.', '若い人は夜ふかしをする傾向がある。'],
      clue: { t: 'parts', text: 'tend（No.10 の動詞）＋ to ＋ 動詞の原形' }, memo: 'No.10 の tend は、ほとんどこの形で使う' },
    { id: 'amount', s: 'P1', ref: 'No.6', w: 'amount', pos: 'n', ja: '額・量',
      ex: ['A large {amount} of money was spent on the project.', 'その計画に多額のお金が使われた。'],
      clue: { t: 'ctx', text: '🧾 レシートのいちばん下：合計の◯◯' }, memo: 'an amount of ＋ 数えられない名詞。数えられるものは a number of' },
    { id: 'earn', s: 'P1', ref: 'No.9', w: 'earn', pos: 'v', ja: '稼ぐ',
      ex: ['She {earns} money by teaching piano.', '彼女はピアノを教えてお金を稼いでいる。'],
      clue: { t: 'ctx', text: '💴 アルバイトをして、お金を…' }, memo: 'earn a living＝生計を立てる' },
    { id: 'overseas', s: 'P1', ref: 'No.14', w: 'overseas', pos: 'n', ja: '海外',
      ex: ['Many students come here from {overseas}.', '多くの学生が海外からここに来る。'],
      clue: { t: 'parts', text: 'over（〜を越えて）＋ seas（海）' }, memo: 'go overseas（海外へ行く）のように副詞としてもよく使う。to はつけない' },

    /* ---------------- Part 2 ---------------- */
    { id: 'harsh', s: 'P2', ref: 'No.1', w: 'harsh', pos: 'adj', ja: '過酷な', def: 'very severe and unpleasant to live in', defJa: 'とても厳しく、暮らすにはつらい',
      ex: ['Life in the desert is {harsh}.', '砂漠での生活は過酷だ。'],
      clue: { t: 'def' }, memo: 'harsh words＝きつい言葉。環境・天候・言葉などが厳しいこと' },
    { id: 'sewing', s: 'P2', ref: 'No.2', w: 'sewing', pos: 'n', ja: '縫製', def: 'the activity of making clothes using a needle and thread', defJa: '針と糸を使って服を作る作業',
      ex: ['My grandmother taught me {sewing}.', '祖母が私に裁縫を教えてくれた。'],
      clue: { t: 'def' }, memo: '動詞 sew（縫う。発音は「ソウ」）に -ing。sewing machine＝ミシン' },
    { id: 'humidity', s: 'P2', ref: 'No.3', w: 'humidity', pos: 'n', ja: '湿気', def: 'the amount of water in the air', defJa: '空気の中の水分の量',
      ex: ['The {humidity} in Tokyo is very high in summer.', '東京の夏は湿気がとても高い。'],
      clue: { t: 'def' }, memo: '形容詞は humid（湿気の多い）' },
    { id: 'harmful', s: 'P2', ref: 'No.4', w: 'harmful', pos: 'adj', ja: '有害な', def: "causing damage to something, especially to a person's health or to the environment", defJa: '何かに、とくに人の健康や環境に害を与える',
      ex: ['Smoking is {harmful} to your health.', '喫煙は健康に有害だ。'],
      clue: { t: 'def' }, memo: 'harm（害）＋ -ful（〜に満ちた）。be harmful to A＝Aに有害だ' },
    { id: 'awful', s: 'P2', ref: 'No.5', w: 'awful', pos: 'adj', ja: 'ひどい', def: 'very bad or unpleasant', defJa: 'とても悪い、またはとても不快な',
      ex: ['The weather was {awful} yesterday.', '昨日の天気はひどかった。'],
      clue: { t: 'def' }, memo: 'awe（おそれ）＋ -ful。もとは「おそろしいほどの」' },
    { id: 'possibly', s: 'P2', ref: 'No.6', w: 'possibly', pos: 'adv', ja: 'ひょっとしたら', def: 'used to say that something might be true but not for sure', defJa: '何かが本当かもしれないが、確かではないと言うときに使う',
      ex: ['{Possibly}, he missed the train.', 'ひょっとしたら、彼は電車に乗り遅れたのかもしれない。'],
      clue: { t: 'def' }, memo: 'possible（ありうる）の副詞。maybe・perhaps より可能性が低め' },
    { id: 'occur', s: 'P2', ref: 'No.7', w: 'occur', pos: 'v', ja: '起きる', def: 'to happen', defJa: '起こること',
      ex: ['The accident {occurred} at night.', 'その事故は夜に起きた。'],
      clue: { t: 'def' }, memo: '過去形は occurred（r を重ねる）。名詞は occurrence' },
    { id: 'collapse', s: 'P2', ref: 'No.8', w: 'collapse', pos: 'v', ja: '崩壊する', def: 'to fall down suddenly after breaking apart', defJa: 'ばらばらに壊れたあと、急に崩れ落ちること',
      ex: ['The old bridge {collapsed} in the storm.', 'その古い橋は嵐で崩壊した。'],
      clue: { t: 'def' }, memo: '建物だけでなく、人が倒れる・会社がつぶれるにも使う' },
    { id: 'neglect', s: 'P2', ref: 'No.9', w: 'neglect', pos: 'v', ja: 'を放置する', def: 'to fail to take care of something', defJa: '何かの面倒を見ないこと（世話をおこたること）',
      ex: ["Don't {neglect} your health.", '健康をおろそかにしてはいけない。'],
      clue: { t: 'def' }, memo: 'neg（〜しない）＋ lect（選ぶ・気にかける）' },
    { id: 'cheaply', s: 'P2', ref: 'No.10', w: 'cheaply', pos: 'adv', ja: '安く', def: 'without spending or costing much money', defJa: 'あまりお金を使わずに、またはお金がかからずに',
      ex: ['You can travel {cheaply} by bus.', 'バスなら安く旅行できる。'],
      clue: { t: 'def' }, memo: 'cheap（安い）＋ -ly' },
    { id: 'have_no_choice', s: 'P2', ref: 'No.11', w: 'have no choice but to', use: 'have no choice but to ＋ 動詞の原形', pos: 'phr', ja: 'doするしかない',
      ex: ['We {had no choice but to} cancel the trip.', '私たちは旅行を中止するしかなかった。'],
      clue: { t: 'parts', text: 'no choice（選ぶ道がない）＋ but（〜のほかに）＋ to ＋ 動詞の原形' }, memo: 'but は「〜以外」。to のあとは動詞の原形' },
    { id: 'disaster', s: 'P2', ref: 'No.14', w: 'disaster', pos: 'n', ja: '災害',
      ex: ['The earthquake was a terrible {disaster}.', 'その地震はひどい災害だった。'],
      clue: { t: 'parts', text: 'dis（悪い）＋ aster（星）。悪い星のめぐりあわせ' }, memo: 'natural disaster＝自然災害' },
    { id: 'be_considered', s: 'P2', ref: 'No.15', w: 'be considered to', use: 'be considered to ＋ 動詞の原形', pos: 'phr', ja: '〜であると考えられる',
      ex: ['He {is considered to} be the best player on the team.', '彼はチームで最高の選手だと考えられている。'],
      clue: { t: 'parts', text: 'consider（よく考える）の受け身 ＋ to ＋ 動詞の原形' }, memo: 'be considered (to be) A＝Aだとみなされている' },

    /* ---------------- Part 3 ---------------- */
    { id: 'stretch', s: 'P3', ref: 'No.1', w: 'stretch', pos: 'v', ja: 'を引き伸ばす', def: 'to make something longer or wider', defJa: '何かを長く、または広くすること',
      ex: ["Please don't {stretch} my sweater!", '私のセーターを伸ばさないで！'],
      clue: { t: 'def' }, memo: '体を伸ばす「ストレッチ」も同じ語' },
    { id: 'perfectly', s: 'P3', ref: 'No.2', w: 'perfectly', pos: 'adv', ja: 'まったく', def: 'completely', defJa: '完全に',
      ex: ['Your answer is {perfectly} right.', 'あなたの答えはまったく正しい。'],
      clue: { t: 'def' }, memo: 'perfect（完全な）＋ -ly' },
    { id: 'acceptable', s: 'P3', ref: 'No.3', w: 'acceptable', pos: 'adj', ja: '受け入れられる', def: 'good enough to be used for a particular purpose', defJa: 'ある目的に使うのに十分よい',
      ex: ['This price is {acceptable} to me.', 'この値段なら受け入れられる。'],
      clue: { t: 'def' }, memo: 'accept（受け入れる）＋ -able（〜できる）' },
    { id: 'inexpensive', s: 'P3', ref: 'No.4', w: 'inexpensive', pos: 'adj', ja: '低価格の', def: 'cheap', defJa: '安い',
      ex: ['This restaurant is good and {inexpensive}.', 'このレストランはおいしくて値段も手ごろだ。'],
      clue: { t: 'def' }, memo: 'in（〜でない）＋ expensive（高い）。cheap より「安っぽい」感じがない' },
    { id: 'i_am_afraid', s: 'P3', ref: 'No.5', w: 'I am afraid that', use: 'I am afraid that ＋ 文', pos: 'phr', ja: '…ではないか心配だ',
      ex: ['{I am afraid that} it will rain tomorrow.', '明日は雨が降るのではないかと心配だ。'],
      clue: { t: 'parts', text: 'afraid（こわがって）＋ that ＋ 文' }, memo: "I'm afraid … は「残念ながら…」と、言いにくいことをやわらげるときにも使う" },
    { id: 'close_down', s: 'P3', ref: 'No.6', w: 'close down', pos: 'phr', ja: '閉鎖する',
      ex: ['The factory will {close down} next year.', 'その工場は来年閉鎖する。'],
      clue: { t: 'parts', text: 'close（閉じる）＋ down（すっかり）' }, memo: '店や工場が営業をやめてしまうこと' },
    { id: 'point_of_view', s: 'P3', ref: 'No.9', w: 'point of view', pos: 'phr', ja: '視点',
      ex: ['From my {point of view}, the plan is too expensive.', '私の視点から見ると、その計画は高すぎる。'],
      clue: { t: 'parts', text: 'point（点）＋ of ＋ view（ながめ）' }, memo: "from A's point of view＝Aの視点から見ると" },

    /* ---------------- Part 4 ---------------- */
    { id: 'quality', s: 'P4', ref: 'No.1', w: 'quality', pos: 'n', ja: '質', def: 'how good or bad something is', defJa: '何かがどのくらい良いか、または悪いか',
      ex: ['These shoes are of high {quality}.', 'この靴は質が高い。'],
      clue: { t: 'def' }, memo: 'quantity（量）と区別。high quality＝高品質' },
    { id: 'durable', s: 'P4', ref: 'No.2', w: 'durable', pos: 'adj', ja: '長持ちする', def: 'able to be used for a long time without breaking', defJa: '壊れずに、長い間使える',
      ex: ['This bag is light and {durable}.', 'このかばんは軽くて丈夫だ。'],
      clue: { t: 'def' }, memo: 'dur（続く）＋ -able。during（〜の間）と同じ仲間。long-lasting は「長く続く」' },
    { id: 'frequently', s: 'P4', ref: 'No.3', w: 'frequently', pos: 'adv', ja: '頻繁に', def: 'very often or many times', defJa: 'とてもよく、または何度も',
      ex: ['I {frequently} visit my grandparents.', '私は祖父母をよく訪ねる。'],
      clue: { t: 'def' }, memo: 'frequent（たびたびの）＋ -ly。名詞は frequency（頻度）' },
    { id: 'exploit', s: 'P4', ref: 'No.4', w: 'exploit', pos: 'v', ja: 'を搾取する', def: 'to treat someone unfairly by asking them to do things but paying very little money', defJa: '人にいろいろさせておきながらほとんどお金を払わず、不当に扱うこと',
      ex: ['Some companies {exploit} young workers.', '若い労働者を搾取する会社もある。'],
      clue: { t: 'def' }, memo: '資源などを「開発する・活用する」の意味もある' },
    { id: 'poorly', s: 'P4', ref: 'No.5', w: 'poorly', pos: 'adv', ja: '不十分に', def: 'in a way that is not good enough', defJa: '十分とは言えないやり方で',
      ex: ['The workers are {poorly} paid.', 'その労働者たちは十分な給料をもらっていない。'],
      clue: { t: 'def' }, memo: 'poor（貧しい・下手な）＋ -ly。poorly paid＝給料が安い' },
    { id: 'long_lasting', s: 'P4', ref: 'No.6', w: 'long-lasting', pos: 'adj', ja: '長持ちする', def: 'continuing for a long time', defJa: '長い間続く',
      ex: ['This battery is {long-lasting}.', 'この電池は長持ちする。'],
      clue: { t: 'def' }, memo: 'long（長く）＋ lasting（続く）。durable は「壊れにくい」' },
    { id: 'first_of_all', s: 'P4', ref: 'No.7', w: 'first of all', pos: 'phr', ja: 'まず第一に',
      ex: ['{First of all}, let me introduce myself.', 'まず初めに、自己紹介させてください。'],
      clue: { t: 'ctx', text: '🎤 スピーチで、話の順番を示す最初の一言' }, memo: '話の最初に使うつなぎ言葉。second, finally と続く' },
    { id: 'more_than_anything', s: 'P4', ref: 'No.8', w: 'more than anything else', pos: 'phr', ja: '何よりも',
      ex: ['I want to see my family {more than anything else}.', '何よりも家族に会いたい。'],
      clue: { t: 'parts', text: 'more than（〜より多く）＋ anything else（ほかのどんなもの）' }, memo: '気持ちの強さを表す。above all も近い' },
    { id: 'to_sum_up', s: 'P4', ref: 'No.9', w: 'to sum up', pos: 'phr', ja: '要するに',
      ex: ['{To sum up}, cheap clothes have hidden costs.', '要するに、安い服には見えないコストがある。'],
      clue: { t: 'parts', text: 'sum（合計）＋ up（まとめる）' }, memo: '話の最後にまとめるときのつなぎ言葉' }
  ]
};
